spring:
  application:
    name: gateway

  profiles:
    active: local

app:
  jwtSecret: groupingGauza!
  jwtExpirationInMilliSecond: 86400000

grouping:
  url:
    api: http://127.0.0.1:10754/
    chat: http://127.0.0.1:10756/
  version: v1

---

spring:
  profiles: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/groupings?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: covengers
    password: Covengers2020@
    initialization-mode: always
    sql-script-encoding: UTF-8

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
#    show-sql: true

  sleuth:
    sampler:
      probability: 1.0

  zipkin:
    base-url: http://localhost:9411/

server:
  address: localhost
  port: 10753

---